### ISSUE TITLE
Screen Diagnostics move around when their values change

### ISSUE THREAD

**Issue by Jenson-42** [TanTanDev/binary_greedy_mesher_demo#1]
When running the engine, the values displayed at the bottom change by orders of magnitude, shifting the screen diagnostics display around and making it hard to keep track of any particular diagnostic.

**Comment by Jenson-42** [comment]
I have a local fix working for this, but I'm new to contributing to open source projects on github and I'm not sure how to submit my fix.  Do I need to be assigned to this issue before I can push to a new branch and submit a PR?

**Comment by bantunesfranco** [comment]
You can fork the original repo, push your fix to the fork, then open a PR to merge it into the original repo
